#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Hebrew voice pack for alon-missions.

Runs macOS `say` with the Carmit (he_IL) voice, trims the silence the synth
leaves at both ends, levels every clip to the same peak, and encodes to AAC.
Sentences are assembled at runtime by playing clips back to back, so even
level and tight edges matter more than raw clip quality.

    python3 build_voice.py            # build everything
    python3 build_voice.py n3 q_plus  # rebuild just these ids

Requires macOS with the Carmit voice installed:
    System Settings -> Accessibility -> Spoken Content -> System Voice -> Manage
"""
import array
import base64
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import wave

import clips as clip_defs

VOICE = 'Carmit'
SAMPLE_RATE = 22050
AAC_BITRATE = 48000
PEAK_TARGET = 0.89        # leave headroom so back-to-back clips never clip
SILENCE_THRESHOLD = 0.015  # fraction of full scale that counts as sound
EDGE_PAD_MS = 25           # keep a little air around each word

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, 'clips')


def check_voice():
    out = subprocess.run(['say', '-v', '?'], capture_output=True, text=True).stdout
    if VOICE not in out:
        sys.exit(
            f"The '{VOICE}' voice is not installed.\n"
            "Install it: System Settings -> Accessibility -> Spoken Content ->\n"
            "System Voice -> Manage Voices -> Hebrew -> Carmit."
        )


def synth(text, rate, wav_path):
    subprocess.run(
        ['say', '-v', VOICE, '-r', str(rate),
         '--file-format=WAVE', f'--data-format=LEI16@{SAMPLE_RATE}',
         '-o', wav_path, text],
        check=True,
    )


def read_wav(path):
    with wave.open(path, 'rb') as w:
        if w.getsampwidth() != 2 or w.getnchannels() != 1:
            raise RuntimeError(f'{path}: expected 16-bit mono')
        samples = array.array('h')
        samples.frombytes(w.readframes(w.getnframes()))
        return samples, w.getframerate()


def write_wav(path, samples, rate):
    with wave.open(path, 'wb') as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(samples.tobytes())


def trim_and_level(samples, rate):
    """Strip leading/trailing silence, then normalize the peak."""
    threshold = int(SILENCE_THRESHOLD * 32767)
    start, end = 0, len(samples)
    while start < end and abs(samples[start]) < threshold:
        start += 1
    while end > start and abs(samples[end - 1]) < threshold:
        end -= 1
    if start >= end:
        raise RuntimeError('clip is silent')

    pad = int(EDGE_PAD_MS * rate / 1000)
    start = max(0, start - pad)
    end = min(len(samples), end + pad)
    trimmed = samples[start:end]

    peak = max(abs(s) for s in trimmed)
    gain = (PEAK_TARGET * 32767) / peak
    return array.array('h', [
        max(-32768, min(32767, int(s * gain))) for s in trimmed
    ])


def encode_aac(wav_path, m4a_path):
    subprocess.run(
        ['afconvert', '-f', 'm4af', '-d', 'aac', '-b', str(AAC_BITRATE),
         wav_path, m4a_path],
        check=True, capture_output=True,
    )


def write_pack_js(manifest):
    """Emit voice/pack.js — the manifest plus every clip as base64.

    A <script> tag is the only way to ship data that works both over http and
    from a file:// page opened straight out of Finder; fetch() is blocked there,
    and when it fails the game has neither audio nor the Hebrew text it draws
    the reading and letter answers from.
    """
    audio = {}
    for cid in manifest:
        path = os.path.join(OUT_DIR, cid + '.m4a')
        with open(path, 'rb') as f:
            audio[cid] = base64.b64encode(f.read()).decode('ascii')

    payload = json.dumps(
        {'manifest': {k: {'text': v['text'], 'duration': v['duration']}
                      for k, v in manifest.items()},
         'audio': audio},
        ensure_ascii=False, separators=(',', ':'))

    out = os.path.join(HERE, 'pack.js')
    with io.open(out, 'w', encoding='utf-8') as f:
        f.write('// Generated by build_voice.py \u2014 do not edit.\n')
        f.write('window.VOICE_PACK = ' + payload + ';\n')
    return out, os.path.getsize(out)


def build(only=None):
    check_voice()
    os.makedirs(OUT_DIR, exist_ok=True)
    all_clips = clip_defs.build()

    targets = all_clips if not only else {k: all_clips[k] for k in only}
    for unknown in set(only or []) - set(all_clips):
        sys.exit(f'Unknown clip id: {unknown}')

    manifest = {}
    tmp = tempfile.mkdtemp(prefix='voice-')
    try:
        for clip_id, (text, rate) in targets.items():
            raw = os.path.join(tmp, f'{clip_id}.raw.wav')
            clean = os.path.join(tmp, f'{clip_id}.wav')
            out = os.path.join(OUT_DIR, f'{clip_id}.m4a')

            synth(text, rate, raw)
            samples, sr = read_wav(raw)
            samples = trim_and_level(samples, sr)
            write_wav(clean, samples, sr)
            if os.path.exists(out):
                os.remove(out)
            encode_aac(clean, out)

            duration = len(samples) / sr
            manifest[clip_id] = {
                'text': text,
                'duration': round(duration, 3),
                'bytes': os.path.getsize(out),
            }
            print(f'  {clip_id:16} {duration:5.2f}s  {text}')
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    # A partial rebuild must not drop the other entries.
    manifest_path = os.path.join(HERE, 'manifest.json')
    if only and os.path.exists(manifest_path):
        with open(manifest_path, encoding='utf-8') as f:
            merged = json.load(f)
        merged.update(manifest)
        manifest = merged

    ordered = {k: manifest[k] for k in all_clips if k in manifest}
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(ordered, f, ensure_ascii=False, indent=2)

    total = sum(e['bytes'] for e in ordered.values())
    print(f'\n{len(targets)} clip(s) built. '
          f'Pack: {len(ordered)} clips, {total / 1024:.0f} KB')

    # Always regenerate, even after a one-clip rebuild, so pack.js can never
    # drift from clips/.
    pack_path, pack_size = write_pack_js(ordered)
    print(f'{os.path.basename(pack_path)}: {pack_size / 1024:.0f} KB')


if __name__ == '__main__':
    build(only=sys.argv[1:] or None)
